### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Temujin0** [compiz-reloaded/emerald#3] opened 2016-03-13 13:01 UTC
It appears on my system emerald has a memory leak. It starts out at 55 megs and after 8 hours with the same windows open it runs up to 100+. Is this a know issue or just my system? Any idea how to diagnose this. I had a trouble before here . Could this affected it. TIA

Edit:Reason for leak found.It seems in emerald that if you hold the cursor over the minimize,restore window or close window it drives the memory use of emerald up.Found this by using valgrind.

Command used
Code:

valgrind -v --tool=memcheck --leak-check=full emerald --replace

I tried this with two different themes and both acted the same way.Scaled black mod and grey-neu

Maybe someone can reproduce it on their system.Maybe it's just my system.

I'll save the terminal output if someone wants it.If so post here.

A little more testing and it seems intermittent also closing a tab in firefox will get it to jump.
Last edited by Temujin; Yesterday at 01:50 AM. Reason: Reason for leak found 

If you need anything from me let me know. I posted here about it and it was reproduced by another user.
[http://forums.fedoraforum.org/showthread.php?t=276286&page=30](url)

**Comment by zezic** [comment] 2016-03-14 08:43
I'm also affected by Emerald memleak. Found that it uses about 600MB with xrestop on my machine and Xorg memory usage grows with it.
If you post additional info about how to use valgrind to find memleak i can try to confirm that it is caused by hovering over buttons.
Btw, seems that Emerald doesn't leak on my machine with Intel graphics, it leak only on Nvidia one with proprietary drivers.
I see this valgrind messages in Intel machine when opening and closing Firefox tabs:
```
--6610-- memcheck GC: 2827 nodes, 996 survivors (35.2%)
--6610-- memcheck GC: 2869 new table size (driftup)
--6610-- memcheck GC: 2869 nodes, 1000 survivors (34.9%)
--6610-- memcheck GC: 2912 new table size (driftup)
--6610-- memcheck GC: 2912 nodes, 1004 survivors (34.5%)
--6610-- memcheck GC: 2955 new table size (driftup)
--6610-- memcheck GC: 2955 nodes, 1026 survivors (34.7%)
--6610-- memcheck GC: 2999 new table size (driftup)
--6610-- memcheck GC: 2999 nodes, 991 survivors (33.0%)
--6610-- memcheck GC: 3043 new table size (driftup)
--6610-- memcheck GC: 3043 nodes, 1009 survivors (33.2%)
--6610-- memcheck GC: 3088 new table size (driftup)
```

**Comment by zezic** [comment] 2016-03-14 23:25
When come home found 3.42GB X memory usage on Nvidia machine.
Now running emerald with

valgrind -v --tool=memcheck --leak-check=full emerald --replace

and noticed activity in valgrind output when resizing windows.
Resize Mode is "Normal" and i assume that Emerald redraw decorations many times when I resize window.
Setting Resize Mode to "Rectangle", "Outline" or "Stretch" makes Emerald less active, memory usage in xrestop still grows (not so fast when in normal resize mode).
But X memory usage stays around 100MB.
I think, now I should check this without valgrind.

**Comment by zezic** [comment] 2016-03-14 23:29
**CONFIRMED**: Emerald eats memory like crazy when it redraws decorations during window resize.
I can reach any number of GBs i want in seconds just by resizing window!

**Comment by zezic** [comment] 2016-03-15 01:27
Resize memleak problem probably fixed in #2

**Comment by XRevan86** [comment] 2016-03-16 13:04
@zezic, yes, you did it :-).

**Closed by XRevan86** 2016-03-16 13:04 UTC

**Comment by raveit65** [comment] 2016-03-16 22:55
@Temujin0 
I've built emerald-0.8.12.2 for /f24/f23/f22
https://bodhi.fedoraproject.org/updates/FEDORA-2016-8925f2673f
https://bodhi.fedoraproject.org/updates/FEDORA-2016-2ec31d26d4
https://bodhi.fedoraproject.org/updates/FEDORA-2016-34b7c03915
Please test

**Comment by Temujin0** [comment] 2016-03-18 04:13
Tested these all day today and everything seems to be working correctly. Nice work to both of you.

Tested on k23(korora) nvidia driver 340.96
